### ISSUE TITLE
error while running get_em_image

### ISSUE THREAD

**Issue by SridharJagannathan** [JaneliaSciComp/neuronbridge-python#1]
Hello @krokicki 
I tried to run some basic examples in the neuronbridge-python client, I get an error as below. To reproduce the same:
```
from neuronbridge import client as nbclient
nbclient = nbclient.Client()
em_image = nbclient.get_em_image(636798093) 
```
The error was:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 em_image = nbclient.get_em_image(636798093)

File ~/Documents/dev/Python/neuronbridge-python/neuronbridge/client.py:52, in Client.get_em_image(self, body_id)
     49 if res.status_code != 200:
     50     raise Exception("Could not retrieve "+url)
---> 52 images = EMImageLookup(**res.json()).results
     53 if not images: return None
     54 return images[0]

NameError: name 'EMImageLookup' is not defined

```

I installed the development version of the package. I also tried installing the released versions directly and then I get different error. Could you please let me know how this could be resolved?

Ideally I would like to run the examples in the notebook:
https://github.com/JaneliaSciComp/neuronbridge-python/blob/main/notebooks/python_api_examples.ipynb

with the latest version of the module

**Comment by krokicki** [comment]
Hi @SridharJagannathan and thanks for reporting this.

I fixed the issue and the new release is here: https://pypi.org/project/neuronbridge-python/3.1.1/

Please let me know if you still have any issues after updating.

**Comment by SridharJagannathan** [comment]
Thanks so much for the quick response. It's working better now.
But, I'm also debugging some associated code wherein I get an error at:
```
get_publib_name(matches : List[Match])
```

I get an error like:
```
AttributeError: 'CDSMatch' object has no attribute 'libraryName'
```

**Comment by SridharJagannathan** [comment]
Thanks so much for the quick response, it works perfect now :)
