### ISSUE TITLE
Error when using get_ppp_matches

### ISSUE THREAD

**Issue by sachira-denagamage** [JaneliaSciComp/neuronbridge-python#2]
Hi @krokicki
I am getting an error when running get_ppp_matches. To reproduce:
```
em_image = client.get_em_image(10000)
print(em_image)
ppp_matches = client.get_ppp_matches(em_image)
```

This body ID should have an associated PPPMResults json ('2970434024842986018.json'), but I get the following error:
```
Exception: Could not retrieve https://s3.amazonaws.com/janelia-neuronbridge-data-prod/v3_1_1/metadata/pppresults/2970434024842986018.json
```

I also noticed that when calling body IDs with get_em_image, it defaults to the VNC v0.5 dataset. Is there a way to specify the MANC v1.0 dataset instead?

**Comment by krokicki** [comment]
Hi @sachira-denagamage ,

Thanks for reporting this. There was a typo in the configuration that was pointing an invalid URL for the VNC. We've fixed that, so it should work now.

Great point about get_em_image returning only one image. I added a new method to allow you to retrieve all the EM images given a given ID. You can call this and then choose the MANC:

```
em_images = client.get_em_images(10000)
list(filter(lambda x: x.libraryName=='FlyEM_MANC_v1.0', em_image))
```

**Comment by sachira-denagamage** [comment]
Thanks for the quick fix! Everything seems to be working smoothly, and I really appreciate the addition of the new method.
